package apache

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"apnoro/internal/paths"
)

func slash(p string) string { return filepath.ToSlash(p) }

// q quotes a value for Apache config (forward slashes, escaped quotes).
func q(p string) string {
	return `"` + strings.ReplaceAll(slash(p), `"`, `\"`) + `"`
}

func systemRoot() string {
	if s := os.Getenv("SystemRoot"); s != "" {
		return s
	}
	return `C:\Windows`
}

var modules = []string{
	"authz_core", "authz_host", "dir", "mime", "log_config", "rewrite", "alias",
	"headers", "env", "setenvif", "deflate", "filter", "expires", "socache_shmcb", "ssl", "fcgid",
}

// RenderMain renders the main httpd.conf. It is pure apart from reading %SystemRoot%.
func RenderMain(opts Options, home string, listenHTTPS bool) string {
	opts = withDefaults(opts)
	j := func(p ...string) string { return filepath.Join(append([]string{home}, p...)...) }
	var b strings.Builder
	w := func(format string, a ...any) { fmt.Fprintf(&b, format+"\n", a...) }

	w("# Generated by Apnoro - do not edit; changes are overwritten.")
	w("Define APNORO_HOME %s", q(home))
	w("ServerRoot %s", q(j("apache")))
	w("Listen 127.0.0.1:%d", opts.HTTPPort)
	if listenHTTPS {
		w("Listen 127.0.0.1:%d", opts.HTTPSPort)
	}
	w("")
	for _, m := range modules {
		w("LoadModule %s_module modules/mod_%s.so", m, m)
	}
	w("")
	w("ServerName localhost")
	w("ServerAdmin admin@localhost")
	w("PidFile %s", q(j("run", "httpd-internal.pid")))
	w("ThreadsPerChild 150")
	w("MaxConnectionsPerChild 0")
	w("AcceptFilter http none")
	w("AcceptFilter https none")
	w("EnableSendfile off")
	w("EnableMMAP off")
	w("Timeout 300")
	w("KeepAlive On")
	w("HostnameLookups Off")
	w("ServerTokens Prod")
	w("TypesConfig conf/mime.types")
	w("AddType application/x-compress .Z")
	w("AddType application/x-gzip .gz .tgz")
	w("AddDefaultCharset UTF-8")
	w("DirectoryIndex index.php index.html index.htm")
	w("")
	w("ErrorLog %s", q(j("logs", "apache-error.log")))
	w("LogLevel warn")
	w(`LogFormat "%%h %%l %%u %%t \"%%r\" %%>s %%b \"%%{Referer}i\" \"%%{User-Agent}i\" %%{Host}i" combined`)
	w("CustomLog %s combined", q(j("logs", "apache-access.log")))
	w("")
	w("<Directory />")
	w("    AllowOverride None")
	w("    Require all denied")
	w("</Directory>")
	w(`<Files ".ht*">`)
	w("    Require all denied")
	w("</Files>")
	w("")
	w("AddOutputFilterByType DEFLATE text/html text/plain text/css text/xml application/javascript application/json image/svg+xml")
	w("")
	w("# mod_fcgid: one php-cgi pool per FcgidWrapper command and vhost")
	w("FcgidIOTimeout 300")
	w("FcgidConnectTimeout 20")
	w("FcgidBusyTimeout 300")
	w("FcgidMaxRequestLen 268435456")
	w("FcgidMaxRequestsPerProcess 1000")
	w("FcgidMaxProcessesPerClass 16")
	w("FcgidProcessLifeTime 3600")
	w("FcgidIdleTimeout 600")
	w("FcgidIdleScanInterval 60")
	w("FcgidOutputBufferSize 0")
	w("FcgidPassHeader Authorization")
	for _, l := range fcgidEnv(home) {
		w("%s", l)
	}
	w("")
	w("SSLSessionCache %s", `"shmcb:`+slash(j("run", "ssl_scache"))+`(512000)"`)
	w("SSLSessionCacheTimeout 300")
	w("SSLProtocol all -SSLv3 -TLSv1 -TLSv1.1")
	w("SSLHonorCipherOrder off")
	w("")
	// The first vhost is Apache's fallback for any unknown Host header. Make it
	// deny everything so a DNS-rebinding page (Host: attacker.example resolving
	// to 127.0.0.1) cannot reach the localhost site or phpMyAdmin (root with an
	// empty password by default -> SQL -> INTO OUTFILE -> PHP code execution).
	w("# Fallback for unknown Host headers (DNS rebinding protection)")
	w("<VirtualHost *:%d>", opts.HTTPPort)
	w("    ServerName apnoro-default.invalid")
	w("    DocumentRoot %s", q(j("www")))
	w("    <Location />")
	w("        Require all denied")
	w("    </Location>")
	w("</VirtualHost>")
	w("")
	w("# Default site: http://localhost")
	w("<VirtualHost *:%d>", opts.HTTPPort)
	w("    ServerName localhost")
	w("    ServerAlias 127.0.0.1")
	w("    DocumentRoot %s", q(j("www")))
	if opts.DefaultPHPCGI != "" {
		w("    FcgidInitialEnv PHPRC %s", q(filepath.Dir(opts.DefaultPHPCGI)))
	}
	b.WriteString(dirBlock(j("www"), opts.DefaultPHPCGI))
	w("    Alias /phpmyadmin %s", q(j("apps", "phpmyadmin")))
	b.WriteString(dirBlock(j("apps", "phpmyadmin"), opts.DefaultPHPCGI))
	w("</VirtualHost>")
	w("")
	w("IncludeOptional %s", q(j("conf", "sites", "*.conf")))
	return b.String()
}

func fcgidEnv(home string) []string {
	tmp := filepath.Join(home, "tmp")
	return []string{
		"FcgidInitialEnv SystemRoot " + q(systemRoot()),
		"FcgidInitialEnv SystemDrive " + q(filepath.VolumeName(systemRoot())),
		`FcgidInitialEnv PATHEXT ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC"`,
		"FcgidInitialEnv TEMP " + q(tmp),
		"FcgidInitialEnv TMP " + q(tmp),
		"FcgidInitialEnv PHP_FCGI_MAX_REQUESTS 1000",
	}
}

// dirBlock renders a <Directory> section that runs .php through php-cgi.
func dirBlock(dir, phpCGI string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "    <Directory %s>\n", q(dir))
	b.WriteString("        Options Indexes FollowSymLinks ExecCGI\n")
	b.WriteString("        AllowOverride All\n")
	b.WriteString("        Require all granted\n")
	b.WriteString("        DirectoryIndex index.php index.html index.htm\n")
	if phpCGI != "" {
		b.WriteString("        <FilesMatch \"\\.php$\">\n")
		b.WriteString("            SetHandler fcgid-script\n")
		b.WriteString("        </FilesMatch>\n")
		fmt.Fprintf(&b, "        FcgidWrapper %s .php\n", q(phpCGI))
	}
	b.WriteString("    </Directory>\n")
	return b.String()
}

// RenderVHost renders one site's config: a *:http vhost, plus a *:https vhost when Secure.
func RenderVHost(v VHost, opts Options) string {
	opts = withDefaults(opts)
	var b strings.Builder
	w := func(format string, a ...any) { fmt.Fprintf(&b, format+"\n", a...) }
	body := func() {
		w("    ServerName %s", v.Domain)
		if len(v.Aliases) > 0 {
			w("    ServerAlias %s", strings.Join(v.Aliases, " "))
		}
		w("    DocumentRoot %s", q(v.DocRoot))
		w("    FcgidInitialEnv PHPRC %s", q(filepath.Dir(v.PHPCGI)))
		b.WriteString(dirBlock(v.DocRoot, v.PHPCGI))
	}
	w("# Generated by Apnoro for %s", v.Domain)
	w("<VirtualHost *:%d>", opts.HTTPPort)
	body()
	w("</VirtualHost>")
	if v.Secure && v.CertFile != "" && v.KeyFile != "" {
		w("")
		w("<VirtualHost *:%d>", opts.HTTPSPort)
		body()
		w("    SSLEngine on")
		w("    SSLCertificateFile %s", q(v.CertFile))
		w("    SSLCertificateKeyFile %s", q(v.KeyFile))
		w("    RequestHeader set X-Forwarded-Proto \"https\"")
		w("</VirtualHost>")
	}
	return b.String()
}

const welcomePHP = `<?php
if (isset($_GET['phpinfo'])) { phpinfo(); exit; }
?><!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Apnoro</title>
<style>
body{font-family:system-ui,-apple-system,"Segoe UI",sans-serif;background:#f6f7f9;color:#1d2330;margin:0;padding:48px 16px}
main{max-width:640px;margin:0 auto;background:#fff;border-radius:12px;padding:32px;box-shadow:0 1px 3px rgba(0,0,0,.08)}
h1{margin:0 0 8px}a{color:#2f5bea}li{margin:6px 0}code{background:#eef0f4;padding:2px 6px;border-radius:4px}
@media (prefers-color-scheme:dark){body{background:#12141a;color:#e6e8ee}main{background:#1b1e26}code{background:#262a35}a{color:#8aa6ff}}
</style></head>
<body><main>
<h1>Apnoro is running</h1>
<p>Apache <?= htmlspecialchars(explode(' ', $_SERVER['SERVER_SOFTWARE'] ?? 'Apache')[0]) ?> &middot; PHP <?= PHP_VERSION ?></p>
<ul>
<li><a href="/?phpinfo=1">phpinfo()</a></li>
<li><a href="/phpmyadmin/">phpMyAdmin</a></li>
</ul>
<p>Put projects in your parked folder and open them at <code>http://&lt;folder&gt;.test</code>.</p>
</main></body></html>
`

func ensureWelcome() error {
	p := filepath.Join(paths.WWWDir(), "index.php")
	if _, err := os.Stat(p); err == nil {
		return nil
	}
	if err := os.WriteFile(p, []byte(welcomePHP), 0o644); err != nil {
		return fmt.Errorf("apache: write welcome page: %w", err)
	}
	return nil
}
