<#
.SYNOPSIS
  Publishes an installer to the website: website/uploads/<version>/<file> plus the
  release list (website/releases.json and website/releases.js) the page renders.

.EXAMPLE
  powershell -ExecutionPolicy Bypass -File scripts\publish-site.ps1 -Version 1.0.0 -Build 20 -Installer dist\AMPLS-Setup-1.0.0.exe

  build.ps1 runs this automatically after compiling the installer (unless -SkipSite).
  Installers are git-ignored: upload the whole website/ folder to the web host.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$Version,
    [Parameter(Mandatory)][string]$Build,
    [Parameter(Mandatory)][string]$Installer,
    # release date (yyyy-MM-dd); defaults to today
    [string]$Date = (Get-Date -Format 'yyyy-MM-dd')
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$Root = Split-Path -Parent $PSScriptRoot
$Site = Join-Path $Root 'website'
if (-not (Test-Path $Installer)) { throw "installer not found: $Installer" }
if ($Version -notmatch '^[0-9A-Za-z.\-]+$') { throw "invalid version: $Version" }

# ---------------------------------------------------------------- copy the installer
$name = Split-Path -Leaf $Installer
$destDir = Join-Path $Site "uploads\$Version"
New-Item -ItemType Directory -Force $destDir | Out-Null
$dest = Join-Path $destDir $name
Copy-Item -Force $Installer $dest
$item = Get-Item $dest
$sha = (Get-FileHash -Algorithm SHA256 $dest).Hash.ToLowerInvariant()

# ---------------------------------------------------------------- bundled component versions
$components = [ordered]@{}
$vj = Join-Path $Root 'dist\payload\versions.json'
if (Test-Path $vj) {
    $v = Get-Content $vj -Raw | ConvertFrom-Json
    foreach ($p in $v.PSObject.Properties) {
        if ($p.Name -notin @('apache', 'mod_fcgid', 'php', 'mysql', 'phpmyadmin', 'composer')) { continue }
        $val = $p.Value
        if ($val -is [psobject] -and $val.PSObject.Properties['version']) { $val = $val.version }
        if ($val -is [string] -or $val -is [ValueType]) { $components[$p.Name] = "$val" }
    }
}

# ---------------------------------------------------------------- release list
$jsonPath = Join-Path $Site 'releases.json'
$releases = @()
if (Test-Path $jsonPath) {
    $existing = Get-Content $jsonPath -Raw | ConvertFrom-Json
    $releases = @($existing.releases | Where-Object { $_.version -ne $Version })
}
$entry = [pscustomobject][ordered]@{
    version    = $Version
    build      = [int]$Build
    date       = $Date
    file       = "uploads/$Version/$name"
    size       = $item.Length
    sha256     = $sha
    components = [pscustomobject]$components
}
$releases = @($entry) + $releases

# newest first: numeric version compare, build number as tie-breaker
function VersionKey($r) {
    $core = ($r.version -split '-')[0]
    $parts = @($core -split '\.' | ForEach-Object { [int]("0$_" -replace '\D', '') })
    while ($parts.Count -lt 3) { $parts += 0 }
    '{0:D6}.{1:D6}.{2:D6}.{3:D8}' -f $parts[0], $parts[1], $parts[2], [int]$r.build
}
$releases = @($releases | Sort-Object -Property @{ Expression = { VersionKey $_ }; Descending = $true })

$data = [pscustomobject][ordered]@{
    product  = 'AMPLS'
    latest   = $releases[0].version
    updated  = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')
    releases = $releases
}
$json = ConvertTo-Json -InputObject $data -Depth 6
$utf8 = New-Object System.Text.UTF8Encoding($false)
[IO.File]::WriteAllText($jsonPath, $json + "`n", $utf8)
[IO.File]::WriteAllText((Join-Path $Site 'releases.js'),
    "// Generated by scripts/publish-site.ps1 - do not edit.`nwindow.AMPLS_RELEASES = $json;`n", $utf8)

Write-Host ("    {0} -> uploads/{1}/{2} (build {3}, {4:N1} MB)" -f $Version, $Version, $name, $Build, ($item.Length / 1MB)) -ForegroundColor Green
