// Generated by scripts/publish-site.ps1 - do not edit.
window.AMPLS_RELEASES = {
    "product":  "AMPLS",
    "latest":  "1.0.0",
    "updated":  "2026-10-01T10:09:59Z",
    "releases":  [
                     {
                         "version":  "1.0.0",
                         "build":  19,
                         "date":  "2026-10-01",
                         "file":  "uploads/1.0.0/AMPLS-Setup-1.0.0.exe",
                         "size":  83344150,
                         "sha256":  "cdcf58b098c1e6f6c9b4a20177de36fd261485ca5ed5dce3994a27ec34c961a9",
                         "components":  {
                                            "apache":  "2.4.68",
                                            "mod_fcgid":  "2.3.10",
                                            "php":  "8.5.11",
                                            "mysql":  "8.4.11",
                                            "phpmyadmin":  "5.2.3",
                                            "composer":  "2.10.3"
                                        }
                     }
                 ]
};
