// Generated by scripts/publish-site.ps1 - do not edit.
window.APNORO_RELEASES = {
    "product":  "Apnoro",
    "latest":  "1.0.0",
    "updated":  "2026-10-02T08:14:22Z",
    "releases":  [
                     {
                         "version":  "1.0.0",
                         "build":  23,
                         "date":  "2026-10-02",
                         "file":  "uploads/1.0.0/Apnoro-Setup-1.0.0.exe",
                         "size":  83714644,
                         "sha256":  "c13d02279858c698ac28f4c78eda9840d565ce224359621f414c0f4b363ee446",
                         "components":  {
                                            "apache":  "2.4.68",
                                            "mod_fcgid":  "2.3.10",
                                            "php":  "8.5.11",
                                            "mysql":  "8.4.11",
                                            "phpmyadmin":  "5.2.3",
                                            "composer":  "2.10.3"
                                        }
                     }
                 ]
};
