// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function AppVersion():Promise<string>;

export function CreateDatabase(arg1:string):Promise<void>;

export function DropDatabase(arg1:string):Promise<void>;

export function ExportDatabase(arg1:string,arg2:string):Promise<void>;

export function GetPHPSettings(arg1:string):Promise<api.PHPSettings>;

export function GetSettings():Promise<api.Settings>;

export function HideWindow():Promise<void>;

export function ImportSQL(arg1:string,arg2:string):Promise<void>;

export function InstallPHP(arg1:string):Promise<void>;

export function Link(arg1:string,arg2:string):Promise<void>;

export function ListDatabases():Promise<Array<api.Database>>;

export function ListPHP():Promise<Array<api.PHPVersion>>;

export function ListSites():Promise<Array<api.Site>>;

export function LogNames():Promise<Array<string>>;

export function MySQLInfo():Promise<api.MySQLInfo>;

export function NewProject(arg1:api.NewProjectRequest):Promise<api.Site>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenPath(arg1:string):Promise<void>;

export function OpenTerminal(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function Overview():Promise<api.Overview>;

export function PHPIniPath(arg1:string):Promise<string>;

export function Park(arg1:string):Promise<void>;

export function Quit():Promise<void>;

export function ReadLog(arg1:string,arg2:number):Promise<string>;

export function RemovePHP(arg1:string):Promise<void>;

export function RestartAll():Promise<void>;

export function RestartService(arg1:string):Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<string>;

export function SavePHPSettings(arg1:api.PHPSettings):Promise<void>;

export function SaveSettings(arg1:api.Settings):Promise<void>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SelectFile(arg1:string,arg2:string):Promise<string>;

export function SetDefaultPHP(arg1:string):Promise<void>;

export function SetMySQLPassword(arg1:string):Promise<void>;

export function SetSitePHP(arg1:string,arg2:string):Promise<void>;

export function SetSiteSecure(arg1:string,arg2:boolean):Promise<void>;

export function ShowWindow():Promise<void>;

export function StartAll():Promise<void>;

export function StartService(arg1:string):Promise<void>;

export function StopAll():Promise<void>;

export function StopService(arg1:string):Promise<void>;

export function TrustCA():Promise<void>;

export function Unlink(arg1:string):Promise<void>;

export function Unpark(arg1:string):Promise<void>;
