// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function CreateDatabase(arg1) {
  return window['go']['main']['App']['CreateDatabase'](arg1);
}

export function DetectEnvironments() {
  return window['go']['main']['App']['DetectEnvironments']();
}

export function DropDatabase(arg1) {
  return window['go']['main']['App']['DropDatabase'](arg1);
}

export function ExportDatabase(arg1, arg2) {
  return window['go']['main']['App']['ExportDatabase'](arg1, arg2);
}

export function GetPHPSettings(arg1) {
  return window['go']['main']['App']['GetPHPSettings'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function ImportSQL(arg1, arg2) {
  return window['go']['main']['App']['ImportSQL'](arg1, arg2);
}

export function InstallPHP(arg1) {
  return window['go']['main']['App']['InstallPHP'](arg1);
}

export function Link(arg1, arg2) {
  return window['go']['main']['App']['Link'](arg1, arg2);
}

export function ListDatabases() {
  return window['go']['main']['App']['ListDatabases']();
}

export function ListPHP() {
  return window['go']['main']['App']['ListPHP']();
}

export function ListSites() {
  return window['go']['main']['App']['ListSites']();
}

export function LogNames() {
  return window['go']['main']['App']['LogNames']();
}

export function MySQLInfo() {
  return window['go']['main']['App']['MySQLInfo']();
}

export function NewProject(arg1) {
  return window['go']['main']['App']['NewProject'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function OpenTerminal(arg1) {
  return window['go']['main']['App']['OpenTerminal'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function Overview() {
  return window['go']['main']['App']['Overview']();
}

export function PHPIniPath(arg1) {
  return window['go']['main']['App']['PHPIniPath'](arg1);
}

export function Park(arg1) {
  return window['go']['main']['App']['Park'](arg1);
}

export function PortConflicts() {
  return window['go']['main']['App']['PortConflicts']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ReadLog(arg1, arg2) {
  return window['go']['main']['App']['ReadLog'](arg1, arg2);
}

export function RemovePHP(arg1) {
  return window['go']['main']['App']['RemovePHP'](arg1);
}

export function RestartAll() {
  return window['go']['main']['App']['RestartAll']();
}

export function RestartService(arg1) {
  return window['go']['main']['App']['RestartService'](arg1);
}

export function RunImport(arg1) {
  return window['go']['main']['App']['RunImport'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SavePHPSettings(arg1) {
  return window['go']['main']['App']['SavePHPSettings'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ScanImport(arg1, arg2) {
  return window['go']['main']['App']['ScanImport'](arg1, arg2);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function SelectFile(arg1, arg2) {
  return window['go']['main']['App']['SelectFile'](arg1, arg2);
}

export function SetDefaultPHP(arg1) {
  return window['go']['main']['App']['SetDefaultPHP'](arg1);
}

export function SetMySQLPassword(arg1) {
  return window['go']['main']['App']['SetMySQLPassword'](arg1);
}

export function SetSitePHP(arg1, arg2) {
  return window['go']['main']['App']['SetSitePHP'](arg1, arg2);
}

export function SetSiteSecure(arg1, arg2) {
  return window['go']['main']['App']['SetSiteSecure'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartAll() {
  return window['go']['main']['App']['StartAll']();
}

export function StartService(arg1) {
  return window['go']['main']['App']['StartService'](arg1);
}

export function StopAll() {
  return window['go']['main']['App']['StopAll']();
}

export function StopEnvironment(arg1) {
  return window['go']['main']['App']['StopEnvironment'](arg1);
}

export function StopService(arg1) {
  return window['go']['main']['App']['StopService'](arg1);
}

export function TrustCA() {
  return window['go']['main']['App']['TrustCA']();
}

export function Unlink(arg1) {
  return window['go']['main']['App']['Unlink'](arg1);
}

export function Unpark(arg1) {
  return window['go']['main']['App']['Unpark'](arg1);
}
