// Package mysql manages the bundled MySQL server: config, initialization and
// simple administration (databases, import/export, root password).
package mysql

import (
	"context"
	"database/sql"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"time"

	driver "github.com/go-sql-driver/mysql"

	"ampls/internal/api"
	"ampls/internal/download"
	"ampls/internal/paths"
	"ampls/internal/services"
)

func slash(p string) string { return filepath.ToSlash(p) }

func binPath(name string) string { return filepath.Join(paths.MySQLDir(), "bin", paths.Exe(name)) }

// MysqldPath is the server executable.
func MysqldPath() string { return binPath("mysqld") }

// IniPath is <Home>/conf/my.ini.
func IniPath() string { return filepath.Join(paths.ConfDir(), "my.ini") }

// LogPath is the MySQL error log (log-error in my.ini). Use a different file
// (e.g. logs/mysql-console.log) for services.Start's stdout/stderr capture.
func LogPath() string { return filepath.Join(paths.LogsDir(), "mysql.log") }

// StartArgs runs mysqld in the foreground with the AMPLS config.
func StartArgs() []string { return []string{"--defaults-file=" + slash(IniPath())} }

// RenderIni is the pure my.ini renderer.
func RenderIni(port int, home string) string {
	j := func(p ...string) string { return slash(filepath.Join(append([]string{home}, p...)...)) }
	var b strings.Builder
	w := func(format string, a ...any) { fmt.Fprintf(&b, format+"\n", a...) }
	w("# Generated by AMPLS - do not edit; changes are overwritten.")
	w("[mysqld]")
	w("basedir=%q", j("mysql"))
	w("datadir=%q", j("data", "mysql"))
	w("port=%d", port)
	w("bind-address=127.0.0.1")
	w("mysqlx=OFF")
	w("log-error=%q", j("logs", "mysql.log"))
	w("pid-file=%q", j("run", "mysqld-internal.pid"))
	w("tmpdir=%q", j("tmp"))
	w("character-set-server=utf8mb4")
	w("collation-server=utf8mb4_0900_ai_ci")
	w("max_allowed_packet=256M")
	w("innodb_buffer_pool_size=256M")
	w("innodb_redo_log_capacity=128M")
	w("max_connections=200")
	w("sql_mode=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION")
	w("")
	w("[client]")
	w("port=%d", port)
	w("host=127.0.0.1")
	w("default-character-set=utf8mb4")
	return b.String()
}

// WriteConfig writes conf/my.ini.
func WriteConfig(port int) error {
	if port <= 0 {
		port = 3306
	}
	for _, d := range []string{paths.ConfDir(), paths.LogsDir(), paths.RunDir(), paths.TmpDir()} {
		if err := os.MkdirAll(d, 0o755); err != nil {
			return fmt.Errorf("mysql: write config: %w", err)
		}
	}
	if err := os.WriteFile(IniPath(), []byte(RenderIni(port, paths.Home())), 0o644); err != nil {
		return fmt.Errorf("mysql: write config: %w", err)
	}
	return nil
}

// Initialized reports whether the datadir holds an initialized server.
func Initialized() bool {
	for _, p := range []string{"mysql.ibd", "mysql"} {
		if _, err := os.Stat(filepath.Join(paths.MySQLDataDir(), p)); err == nil {
			return true
		}
	}
	return false
}

// Initialize runs mysqld --initialize-insecure (root@localhost, empty password).
func Initialize() error {
	if Initialized() {
		return nil
	}
	if _, err := os.Stat(IniPath()); err != nil {
		if err := WriteConfig(3306); err != nil {
			return err
		}
	}
	// datadir must be absent or empty
	if entries, err := os.ReadDir(paths.MySQLDataDir()); err == nil && len(entries) > 0 {
		return fmt.Errorf("mysql: initialize: %s is not empty", paths.MySQLDataDir())
	}
	os.Remove(paths.MySQLDataDir())
	if err := os.MkdirAll(paths.DataDir(), 0o755); err != nil {
		return fmt.Errorf("mysql: initialize: %w", err)
	}
	// Initialize into a staging dir and rename on success, so an interrupted
	// init never leaves a half-built datadir that looks initialized.
	stage := paths.MySQLDataDir() + ".init"
	os.RemoveAll(stage)
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
	defer cancel()
	cmd := exec.CommandContext(ctx, MysqldPath(), "--defaults-file="+slash(IniPath()), "--datadir="+slash(stage), "--initialize-insecure", "--console")
	cmd.Dir = filepath.Dir(MysqldPath())
	services.Hide(cmd)
	out, err := cmd.CombinedOutput()
	if err != nil {
		os.RemoveAll(stage)
		return fmt.Errorf("mysql: initialize: %v: %s", err, lastLines(string(out), 10))
	}
	if _, err := os.Stat(filepath.Join(stage, "mysql.ibd")); err != nil {
		os.RemoveAll(stage)
		return fmt.Errorf("mysql: initialize: datadir not created: %s", lastLines(string(out), 10))
	}
	if err := os.Rename(stage, paths.MySQLDataDir()); err != nil {
		return fmt.Errorf("mysql: initialize: %w", err)
	}
	if !Initialized() {
		return fmt.Errorf("mysql: initialize: datadir not created: %s", lastLines(string(out), 10))
	}
	return nil
}

var versionRe = regexp.MustCompile(`Ver\s+([0-9]+\.[0-9]+\.[0-9]+)`)

// Version returns the mysqld version ("8.4.11") or "".
func Version() string {
	if _, err := os.Stat(MysqldPath()); err != nil {
		return ""
	}
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	cmd := exec.CommandContext(ctx, MysqldPath(), "--version")
	services.Hide(cmd)
	out, _ := cmd.CombinedOutput()
	if m := versionRe.FindSubmatch(out); m != nil {
		return string(m[1])
	}
	return ""
}

// InstallFromZip extracts the MySQL winx64 zip into paths.MySQLDir().
func InstallFromZip(zipPath string) error {
	dir := paths.MySQLDir()
	stage := dir + ".staging"
	os.RemoveAll(stage)
	if err := download.Unzip(zipPath, stage, true); err != nil {
		os.RemoveAll(stage)
		return fmt.Errorf("mysql: install: %w", err)
	}
	if _, err := os.Stat(filepath.Join(stage, "bin", paths.Exe("mysqld"))); err != nil {
		os.RemoveAll(stage)
		return fmt.Errorf("mysql: install: mysqld not found in %s", filepath.Base(zipPath))
	}
	if _, err := os.Stat(dir); err == nil {
		old := dir + ".old"
		os.RemoveAll(old)
		if err := os.Rename(dir, old); err != nil {
			os.RemoveAll(stage)
			return fmt.Errorf("mysql: install (is MySQL running?): %w", err)
		}
		defer os.RemoveAll(old)
	}
	if err := os.Rename(stage, dir); err != nil {
		return fmt.Errorf("mysql: install: %w", err)
	}
	return nil
}

// ---- SQL ----

func open(port int, password string) (*sql.DB, error) {
	cfg := driver.NewConfig()
	cfg.User = "root"
	cfg.Passwd = password
	cfg.Net = "tcp"
	cfg.Addr = "127.0.0.1:" + strconv.Itoa(port)
	cfg.Timeout = 5 * time.Second
	cfg.ReadTimeout = 60 * time.Second
	cfg.WriteTimeout = 60 * time.Second
	cfg.Params = map[string]string{"information_schema_stats_expiry": "0"}
	c, err := driver.NewConnector(cfg)
	if err != nil {
		return nil, err
	}
	db := sql.OpenDB(c)
	db.SetMaxOpenConns(1)
	return db, nil
}

func withDB(port int, password string, fn func(ctx context.Context, db *sql.DB) error) error {
	db, err := open(port, password)
	if err != nil {
		return fmt.Errorf("mysql: %w", err)
	}
	defer db.Close()
	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()
	return fn(ctx, db)
}

// Ping checks the server accepts root logins.
func Ping(port int, password string) error {
	return withDB(port, password, func(ctx context.Context, db *sql.DB) error {
		ctx, cancel := context.WithTimeout(ctx, 3*time.Second)
		defer cancel()
		if err := db.PingContext(ctx); err != nil {
			return fmt.Errorf("mysql: ping: %w", err)
		}
		return nil
	})
}

// Shutdown asks the server to stop.
func Shutdown(port int, password string) error {
	return withDB(port, password, func(ctx context.Context, db *sql.DB) error {
		if _, err := db.ExecContext(ctx, "SHUTDOWN"); err != nil {
			return fmt.Errorf("mysql: shutdown: %w", err)
		}
		return nil
	})
}

var systemSchemas = map[string]bool{"mysql": true, "information_schema": true, "performance_schema": true, "sys": true}

var dbNameRe = regexp.MustCompile(`^[A-Za-z0-9_]{1,64}$`)

// ValidName reports whether name is an allowed database name.
func ValidName(name string) bool { return dbNameRe.MatchString(name) }

func checkName(name string) error {
	if !ValidName(name) {
		return fmt.Errorf("mysql: invalid database name %q (use letters, digits and _)", name)
	}
	if systemSchemas[strings.ToLower(name)] {
		return fmt.Errorf("mysql: %s is a system database", name)
	}
	return nil
}

func quoteIdent(name string) string { return "`" + strings.ReplaceAll(name, "`", "``") + "`" }

// ListDatabases returns user databases with table counts and sizes.
func ListDatabases(port int, password string) ([]api.Database, error) {
	var out []api.Database
	err := withDB(port, password, func(ctx context.Context, db *sql.DB) error {
		rows, err := db.QueryContext(ctx, `SELECT s.SCHEMA_NAME, COUNT(t.TABLE_NAME),
  COALESCE(SUM(t.DATA_LENGTH + t.INDEX_LENGTH), 0)
FROM information_schema.SCHEMATA s
LEFT JOIN information_schema.TABLES t ON t.TABLE_SCHEMA = s.SCHEMA_NAME
GROUP BY s.SCHEMA_NAME ORDER BY s.SCHEMA_NAME`)
		if err != nil {
			return fmt.Errorf("mysql: list databases: %w", err)
		}
		defer rows.Close()
		for rows.Next() {
			var d api.Database
			var size sql.NullFloat64
			if err := rows.Scan(&d.Name, &d.Tables, &size); err != nil {
				return fmt.Errorf("mysql: list databases: %w", err)
			}
			if systemSchemas[strings.ToLower(d.Name)] {
				continue
			}
			d.SizeBytes = int64(size.Float64)
			out = append(out, d)
		}
		return rows.Err()
	})
	return out, err
}

// CreateDatabase creates a utf8mb4 database (no error if it exists).
func CreateDatabase(port int, password, name string) error {
	if err := checkName(name); err != nil {
		return err
	}
	return withDB(port, password, func(ctx context.Context, db *sql.DB) error {
		if _, err := db.ExecContext(ctx, "CREATE DATABASE IF NOT EXISTS "+quoteIdent(name)+" CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"); err != nil {
			return fmt.Errorf("mysql: create database: %w", err)
		}
		return nil
	})
}

// DropDatabase drops a user database.
func DropDatabase(port int, password, name string) error {
	if err := checkName(name); err != nil {
		return err
	}
	return withDB(port, password, func(ctx context.Context, db *sql.DB) error {
		if _, err := db.ExecContext(ctx, "DROP DATABASE IF EXISTS "+quoteIdent(name)); err != nil {
			return fmt.Errorf("mysql: drop database: %w", err)
		}
		return nil
	})
}

func sqlString(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `'`, `\'`, "\x00", `\0`, "\n", `\n`, "\r", `\r`, "\x1a", `\Z`)
	return "'" + r.Replace(s) + "'"
}

// SetRootPassword changes root@localhost's password.
func SetRootPassword(port int, oldPassword, newPassword string) error {
	return withDB(port, oldPassword, func(ctx context.Context, db *sql.DB) error {
		if _, err := db.ExecContext(ctx, "ALTER USER 'root'@'localhost' IDENTIFIED BY "+sqlString(newPassword)); err != nil {
			return fmt.Errorf("mysql: set root password: %w", err)
		}
		return nil
	})
}

// clientDefaults writes a temporary [client] option file holding the password
// so it never appears on a command line. It goes to the per-user temp dir
// (%TEMP% is private to the user), not <Home>/tmp, which every local user can
// read. Caller removes it.
func clientDefaults(port int, password string) (string, error) {
	f, err := os.CreateTemp("", "ampls-client-*.cnf")
	if err != nil {
		return "", err
	}
	if _, err := f.WriteString(renderClientDefaults(port, password)); err != nil {
		f.Close()
		os.Remove(f.Name())
		return "", err
	}
	return f.Name(), f.Close()
}

// renderClientDefaults renders the option file; the password is escaped so a
// newline or quote in it cannot add further options.
func renderClientDefaults(port int, password string) string {
	pw := strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", `\n`, "\r", `\r`, "\t", `\t`, "\x00", "").Replace(password)
	return fmt.Sprintf("[client]\nuser=root\npassword=\"%s\"\nhost=127.0.0.1\nport=%d\ndefault-character-set=utf8mb4\n", pw, port)
}

// Import loads an .sql file into database (created if missing).
func Import(port int, password, database, file string) error {
	if err := CreateDatabase(port, password, database); err != nil {
		return err
	}
	in, err := os.Open(file)
	if err != nil {
		return fmt.Errorf("mysql: import: %w", err)
	}
	defer in.Close()
	cnf, err := clientDefaults(port, password)
	if err != nil {
		return fmt.Errorf("mysql: import: %w", err)
	}
	defer os.Remove(cnf)
	cmd := exec.Command(binPath("mysql"), "--defaults-extra-file="+cnf, "--protocol=TCP", database)
	cmd.Stdin = in
	services.Hide(cmd)
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("mysql: import: %v: %s", err, lastLines(string(out), 5))
	}
	return nil
}

// Export dumps database to file with mysqldump.
func Export(port int, password, database, file string) error {
	if err := checkName(database); err != nil {
		return err
	}
	cnf, err := clientDefaults(port, password)
	if err != nil {
		return fmt.Errorf("mysql: export: %w", err)
	}
	defer os.Remove(cnf)
	cmd := exec.Command(binPath("mysqldump"), "--defaults-extra-file="+cnf, "--protocol=TCP",
		"--single-transaction", "--routines", "--triggers", "--events", "--no-tablespaces",
		"--result-file="+file, database)
	services.Hide(cmd)
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("mysql: export: %v: %s", err, lastLines(string(out), 5))
	}
	return nil
}

func lastLines(s string, n int) string {
	lines := strings.Split(strings.TrimSpace(strings.ReplaceAll(s, "\r", "")), "\n")
	if len(lines) > n {
		lines = lines[len(lines)-n:]
	}
	return strings.Join(lines, " | ")
}
