; AMPLS installer (Inno Setup 6.3+). Build via scripts\build.ps1, or directly:
;   ISCC.exe installer\ampls.iss /DAppVersion=1.0.0
; Inputs (relative to the repo root):
;   dist\app\AMPLS.exe, dist\app\bin\{ampls,php,ampls-helper}.exe, composer.phar, composer.bat
;   dist\payload\...           runtimes in data-dir layout (scripts\fetch-runtimes.ps1)
;   dist\cache\vc_redist.x64.exe
;   assets\icons\app.ico, installer-wizard-*.bmp  (scripts\icon-tool\generate.mjs)

#ifndef AppVersion
  #define AppVersion "0.0.0-dev"
#endif
#ifndef Compression
  ; override for quick validation builds: /DCompression=none
  #define Compression "lzma2/ultra64"
#endif
#define Root ".."
#define AppName "AMPLS"
#define AppExe "AMPLS.exe"
#define HelperService "AMPLSHelper"
#define VCRedist Root + "\dist\cache\vc_redist.x64.exe"
#define VCRedistVersion GetVersionNumbersString(VCRedist)

[Setup]
AppId={{E601BE50-B1E9-4B4D-AB38-CBD52D524511}
AppName={#AppName}
AppVersion={#AppVersion}
AppVerName={#AppName} {#AppVersion}
AppPublisher=Akash Sahay
AppComments=Apache, MySQL, PHP - Latest Software
AppCopyright=Copyright (c) 2026 Akash Sahay
VersionInfoProductName={#AppName}
VersionInfoProductTextVersion={#AppVersion}
VersionInfoDescription={#AppName} Setup
DefaultDirName={autopf}\AMPLS
DefaultGroupName=AMPLS
DisableProgramGroupPage=yes
PrivilegesRequired=admin
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
MinVersion=10.0
Compression={#Compression}
SolidCompression=yes
LZMAUseSeparateProcess=yes
LZMANumBlockThreads=4
WizardStyle=modern
WizardImageFile={#Root}\assets\icons\installer-wizard-large-100.bmp,{#Root}\assets\icons\installer-wizard-large-125.bmp,{#Root}\assets\icons\installer-wizard-large-150.bmp,{#Root}\assets\icons\installer-wizard-large-175.bmp,{#Root}\assets\icons\installer-wizard-large-200.bmp
WizardSmallImageFile={#Root}\assets\icons\installer-wizard-small-100.bmp,{#Root}\assets\icons\installer-wizard-small-125.bmp,{#Root}\assets\icons\installer-wizard-small-150.bmp,{#Root}\assets\icons\installer-wizard-small-175.bmp,{#Root}\assets\icons\installer-wizard-small-200.bmp
SetupIconFile={#Root}\assets\icons\app.ico
UninstallDisplayIcon={app}\{#AppExe}
UninstallDisplayName={#AppName}
ChangesEnvironment=yes
CloseApplications=yes
RestartApplications=no
OutputDir={#Root}\dist
OutputBaseFilename=AMPLS-Setup-{#AppVersion}
SetupLogging=yes

[Messages]
SetupWindowTitle=Setup - %1

[Tasks]
Name: "parksites"; Description: "Create a Sites folder at %USERPROFILE%\AMPLS\Sites and park it"
Name: "addtopath"; Description: "Add ampls, php and composer to PATH"
Name: "trustca"; Description: "Trust the AMPLS local HTTPS certificate"
Name: "autostart"; Description: "Start AMPLS when Windows starts"; Flags: unchecked
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"

[Dirs]
; The GUI and CLI run unelevated and must be able to write everywhere in the data dir.
Name: "{code:GetDataDir}"; Permissions: users-modify; Flags: uninsneveruninstall

[Files]
Source: "{#Root}\dist\app\{#AppExe}"; DestDir: "{app}"; Flags: ignoreversion; AfterInstall: WriteDataDirFile
Source: "{#Root}\dist\app\bin\*"; DestDir: "{app}\bin"; Flags: ignoreversion recursesubdirs createallsubdirs
; Runtimes only (apache\, php\<minor>\, mysql\, apps\, LICENSES\). User data (data\, conf\, certs\,
; config.json, php.ini) is generated by `ampls setup` and never shipped, so upgrades cannot clobber it.
Source: "{#Root}\dist\payload\*"; DestDir: "{code:GetDataDir}"; Excludes: "\apps\phpmyadmin\config.inc.php"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#Root}\dist\payload\apps\phpmyadmin\config.inc.php"; DestDir: "{code:GetDataDir}\apps\phpmyadmin"; Flags: onlyifdoesntexist uninsneveruninstall
Source: "{#VCRedist}"; Flags: dontcopy

[Icons]
Name: "{autoprograms}\AMPLS"; Filename: "{app}\{#AppExe}"
Name: "{autodesktop}\AMPLS"; Filename: "{app}\{#AppExe}"; Tasks: desktopicon

[Registry]
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "AMPLS"; ValueData: """{app}\{#AppExe}"""; Tasks: autostart; Flags: uninsdeletevalue

[Run]
Filename: "{app}\{#AppExe}"; Description: "Launch AMPLS"; Flags: postinstall nowait skipifsilent runasoriginaluser

[UninstallRun]
Filename: "{app}\bin\ampls.exe"; Parameters: "stop"; Flags: runhidden waituntilterminated skipifdoesntexist; RunOnceId: "StopServices"
Filename: "{app}\bin\ampls.exe"; Parameters: "hosts clear"; Flags: runhidden waituntilterminated skipifdoesntexist; RunOnceId: "ClearHosts"
Filename: "{sys}\sc.exe"; Parameters: "stop {#HelperService}"; Flags: runhidden waituntilterminated; RunOnceId: "StopHelper"
Filename: "{app}\bin\ampls-helper.exe"; Parameters: "uninstall"; Flags: runhidden waituntilterminated skipifdoesntexist; RunOnceId: "RemoveHelper"
Filename: "{sys}\certutil.exe"; Parameters: "-delstore Root ""AMPLS Local CA"""; Flags: runhidden waituntilterminated; RunOnceId: "UntrustCA"

[UninstallDelete]
Type: files; Name: "{app}\data-dir.txt"

[Code]
const
  EnvKey = 'SYSTEM\CurrentControlSet\Control\Session Manager\Environment';
  VCKey = 'SOFTWARE\Microsoft\VisualStudio\14.0\VC\Runtimes\x64';
  DefaultDataDir = 'C:\AMPLS';

var
  DataDirPage: TInputDirWizardPage;
  UninstallDataDir: string;

{ ---------- data dir ---------- }

function GetDataDir(Param: string): string;
begin
  if DataDirPage <> nil then
    Result := RemoveBackslashUnlessRoot(Trim(DataDirPage.Values[0]))
  else
    Result := DefaultDataDir;
end;

procedure InitializeWizard;
var
  Def: string;
begin
  DataDirPage := CreateInputDirPage(wpSelectDir,
    'Select Data Location',
    'Where should AMPLS keep Apache, PHP versions, MySQL databases and site configs?',
    'Setup will store AMPLS data in the following folder. Keep the path short and without spaces so Apache and MySQL behave.' + #13#10#13#10 +
    'Your databases and site configuration live here and are kept when you upgrade.',
    False, 'AMPLS');
  DataDirPage.Add('');
  { upgrade: default to the previous data dir; silent installs can pass /DATADIR=D:\AMPLS }
  Def := GetPreviousData('DataDir', DefaultDataDir);
  DataDirPage.Values[0] := ExpandConstant('{param:DATADIR|' + Def + '}');
end;

procedure RegisterPreviousData(PreviousDataKey: Integer);
begin
  SetPreviousData(PreviousDataKey, 'DataDir', GetDataDir(''));
end;

function IsInside(Child, Parent: string): Boolean;
begin
  Child := AddBackslash(Uppercase(Child));
  Parent := AddBackslash(Uppercase(Parent));
  Result := Copy(Child, 1, Length(Parent)) = Parent;
end;

function NextButtonClick(CurPageID: Integer): Boolean;
var
  D, App: string;
begin
  Result := True;
  if CurPageID = DataDirPage.ID then
  begin
    D := GetDataDir('');
    App := RemoveBackslashUnlessRoot(WizardDirValue);
    if (Length(D) < 4) or (Copy(D, 2, 2) <> ':\') then
    begin
      SuppressibleMsgBox('Please choose a folder on a local drive, not a drive root (for example C:\AMPLS).', mbError, MB_OK, IDOK);
      Result := False;
    end
    else if Pos(' ', D) > 0 then
    begin
      SuppressibleMsgBox('The data folder must not contain spaces.' + #13#10 +
        'Apache and MySQL configuration break on paths with spaces. Please choose a path like C:\AMPLS.', mbError, MB_OK, IDOK);
      Result := False;
    end
    else if IsInside(D, App) or IsInside(App, D) then
    begin
      SuppressibleMsgBox('The data folder must be separate from the program folder (' + App + ').', mbError, MB_OK, IDOK);
      Result := False;
    end;
  end;
end;

procedure WriteDataDirFile;
begin
  if not SaveStringToFile(ExpandConstant('{app}\data-dir.txt'), GetDataDir(''), False) then
    Log('Failed to write data-dir.txt');
end;

{ ---------- VC++ runtime ---------- }

function NextVersionPart(var S: string): Integer;
var
  P: Integer;
begin
  P := Pos('.', S);
  if P = 0 then begin Result := StrToIntDef(S, 0); S := ''; end
  else begin Result := StrToIntDef(Copy(S, 1, P - 1), 0); Delete(S, 1, P); end;
end;

function VCRedistNeeded: Boolean;
var
  Installed, Major, Minor, Bld: Cardinal;
  S: string;
  WantMajor, WantMinor, WantBld: Integer;
begin
  S := '{#VCRedistVersion}';
  WantMajor := NextVersionPart(S);
  WantMinor := NextVersionPart(S);
  WantBld := NextVersionPart(S);
  Result := True;
  if RegQueryDWordValue(HKLM64, VCKey, 'Installed', Installed) and (Installed = 1) and
     RegQueryDWordValue(HKLM64, VCKey, 'Major', Major) and
     RegQueryDWordValue(HKLM64, VCKey, 'Minor', Minor) and
     RegQueryDWordValue(HKLM64, VCKey, 'Bld', Bld) then
  begin
    if Major <> WantMajor then Result := Major < WantMajor
    else if Minor <> WantMinor then Result := Minor < WantMinor
    else Result := Bld < WantBld;
    Log(Format('VC++ runtime installed: %d.%d.%d, bundled: {#VCRedistVersion}', [Major, Minor, Bld]));
  end;
end;

{ ---------- PATH ---------- }

function PathContains(PathValue, Dir: string): Boolean;
begin
  PathValue := ';' + Uppercase(PathValue) + ';';
  Result := (Pos(';' + Uppercase(Dir) + ';', PathValue) > 0) or
            (Pos(';' + Uppercase(Dir) + '\;', PathValue) > 0);
end;

procedure AddToSystemPath(Dir: string);
var
  P: string;
begin
  if not RegQueryStringValue(HKLM, EnvKey, 'Path', P) then P := '';
  if PathContains(P, Dir) then exit;
  if (P <> '') and (P[Length(P)] <> ';') then P := P + ';';
  P := P + Dir;
  if not RegWriteExpandStringValue(HKLM, EnvKey, 'Path', P) then
    Log('Failed to update system PATH');
end;

procedure RemoveFromSystemPath(Dir: string);
var
  P, Part, U, NewP: string;
  I: Integer;
begin
  if not RegQueryStringValue(HKLM, EnvKey, 'Path', P) then exit;
  if not PathContains(P, Dir) then exit;
  U := Uppercase(Dir);
  NewP := '';
  P := P + ';';
  while P <> '' do
  begin
    I := Pos(';', P);
    Part := Copy(P, 1, I - 1);
    Delete(P, 1, I);
    if (Part <> '') and (Uppercase(Part) <> U) and (Uppercase(Part) <> U + '\') then
    begin
      if NewP <> '' then NewP := NewP + ';';
      NewP := NewP + Part;
    end;
  end;
  RegWriteExpandStringValue(HKLM, EnvKey, 'Path', NewP);
end;

{ ---------- install steps ---------- }

function RunHidden(Exe, Params, Status: string): Integer;
begin
  if Status <> '' then WizardForm.StatusLabel.Caption := Status;
  Log('Running: "' + Exe + '" ' + Params);
  if not Exec(Exe, Params, '', SW_HIDE, ewWaitUntilTerminated, Result) then
    Result := -1;
  Log(Format('  exit code %d', [Result]));
end;

function PrepareToInstall(var NeedsRestart: Boolean): String;
var
  Code: Integer;
begin
  Result := '';
  { upgrade: stop running services and the helper so their binaries can be replaced }
  if FileExists(ExpandConstant('{app}\bin\ampls.exe')) then
    Exec(ExpandConstant('{app}\bin\ampls.exe'), 'stop', '', SW_HIDE, ewWaitUntilTerminated, Code);
  Exec(ExpandConstant('{sys}\sc.exe'), 'stop {#HelperService}', '', SW_HIDE, ewWaitUntilTerminated, Code);
  Exec(ExpandConstant('{sys}\taskkill.exe'), '/F /IM {#AppExe}', '', SW_HIDE, ewWaitUntilTerminated, Code);
end;

function SetupFlags: string;
begin
  Result := '';
  if WizardIsTaskSelected('parksites') then Result := Result + ' --park-default';
  if WizardIsTaskSelected('trustca') then Result := Result + ' --trust-ca-machine';
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  Code: Integer;
  Home, Bin: string;
begin
  if CurStep <> ssPostInstall then exit;
  Home := GetDataDir('');
  Bin := ExpandConstant('{app}\bin');
  WriteDataDirFile;
  WizardForm.ProgressGauge.Style := npbstMarquee;

  if VCRedistNeeded then
  begin
    ExtractTemporaryFile('vc_redist.x64.exe');
    Code := RunHidden(ExpandConstant('{tmp}\vc_redist.x64.exe'), '/install /quiet /norestart',
      'Installing the Microsoft Visual C++ runtime...');
    { 0 = ok, 1638 = newer already installed, 3010 = ok, reboot required }
    if (Code <> 0) and (Code <> 1638) and (Code <> 3010) then
      SuppressibleMsgBox(Format('The Microsoft Visual C++ runtime installer failed (code %d). Apache and PHP need it; ' +
        'install it from https://aka.ms/vs/17/release/vc_redist.x64.exe', [Code]), mbError, MB_OK, IDOK);
  end;

  if WizardIsTaskSelected('addtopath') then
    AddToSystemPath(Bin);

  Code := RunHidden(Bin + '\ampls.exe', 'setup --home "' + Home + '"' + SetupFlags,
    'Configuring Apache, PHP and MySQL (this can take a minute)...');
  if Code <> 0 then
    SuppressibleMsgBox(Format('AMPLS setup did not finish (code %d).' + #13#10 +
      'You can re-run it later from a terminal:  ampls setup --home "%s"', [Code, Home]), mbError, MB_OK, IDOK);

  Code := RunHidden(Bin + '\ampls-helper.exe', 'install --home "' + Home + '"',
    'Installing the AMPLS hosts helper service...');
  if Code = 0 then
    RunHidden(ExpandConstant('{sys}\sc.exe'), 'start {#HelperService}', '')
  else
    Log('ampls-helper install failed; hosts edits will fall back to UAC prompts');

  WizardForm.ProgressGauge.Style := npbstNormal;
end;

{ ---------- uninstall ---------- }

function InitializeUninstall: Boolean;
var
  S: AnsiString;
begin
  Result := True;
  UninstallDataDir := '';
  if LoadStringFromFile(ExpandConstant('{app}\data-dir.txt'), S) then
    UninstallDataDir := Trim(String(S));
end;

function LooksLikeAmplsHome(D: string): Boolean;
begin
  Result := (Length(D) > 3) and DirExists(D) and
    (FileExists(D + '\config.json') or DirExists(D + '\apache') or DirExists(D + '\mysql'));
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep = usUninstall then
    RemoveFromSystemPath(ExpandConstant('{app}\bin'));

  if (CurUninstallStep = usPostUninstall) and (UninstallDataDir <> '') and LooksLikeAmplsHome(UninstallDataDir) then
  begin
    if SuppressibleMsgBox('Also delete the AMPLS data folder?' + #13#10#13#10 + UninstallDataDir + #13#10#13#10 +
      'This permanently removes ALL MySQL databases, site configs, certificates and logs stored there. ' +
      'Your project folders (Sites) are not touched.' + #13#10#13#10 +
      'Choose No to keep your data for a later reinstall.',
      mbConfirmation, MB_YESNO or MB_DEFBUTTON2, IDNO) = IDYES then
    begin
      if not DelTree(UninstallDataDir, True, True, True) then
        MsgBox('Some files in ' + UninstallDataDir + ' could not be removed. You can delete the folder manually.', mbInformation, MB_OK);
    end;
  end;
end;
