; Apnoro installer (Inno Setup 6.3+). Build via scripts\build.ps1, or directly:
;   ISCC.exe installer\apnoro.iss /DAppVersion=1.0.0
; Inputs (relative to the repo root):
;   dist\app\Apnoro.exe, dist\app\bin\{apnoro,apnoro-helper}.exe, dist\app\shims\{php.exe,composer.phar,composer.bat}
;   dist\payload\...           runtimes in data-dir layout (scripts\fetch-runtimes.ps1)
;   dist\cache\vc_redist.x64.exe
;   assets\icons\app.ico, installer-wizard-*.bmp  (scripts\icon-tool\generate.mjs)

#ifndef AppVersion
  #define AppVersion "0.0.0-dev"
#endif
#ifndef AppBuild
  #define AppBuild "0"
#endif
#ifndef Compression
  ; override for quick validation builds: /DCompression=none
  #define Compression "lzma2/ultra64"
#endif
#define Root ".."
#define AppName "Apnoro"
#define AppExe "Apnoro.exe"
#define HelperService "ApnoroHelper"
#define VCRedist Root + "\dist\cache\vc_redist.x64.exe"
#define VCRedistVersion GetVersionNumbersString(VCRedist)

[Setup]
; New product id for Apnoro. AMPLS (the former name) used {E601BE50-B1E9-4B4D-AB38-CBD52D524511};
; an AMPLS install is migrated in PrepareToInstall (see LegacyAppId).
AppId={{5683CB67-B196-4230-8227-C104737C6F95}
AppName={#AppName}
AppVersion={#AppVersion}
AppVerName={#AppName} {#AppVersion}
AppPublisher=Akash Sahay
AppComments=Apache, PHP and MySQL for Windows
AppCopyright=Copyright (c) 2026 Akash Sahay
VersionInfoProductName={#AppName}
VersionInfoProductTextVersion={#AppVersion} (build {#AppBuild})
; numeric file version a.b.c.build (skipped for pre-release versions like 1.1.0-beta)
#if Pos("-", AppVersion) == 0
VersionInfoVersion={#AppVersion}.{#AppBuild}
#endif
VersionInfoDescription={#AppName} Setup
DefaultDirName={autopf}\Apnoro
DefaultGroupName=Apnoro
DisableProgramGroupPage=yes
PrivilegesRequired=admin
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
MinVersion=10.0
Compression={#Compression}
SolidCompression=yes
LZMAUseSeparateProcess=yes
LZMANumBlockThreads=4
WizardStyle=modern
WizardImageFile={#Root}\assets\icons\installer-wizard-large-100.bmp,{#Root}\assets\icons\installer-wizard-large-125.bmp,{#Root}\assets\icons\installer-wizard-large-150.bmp,{#Root}\assets\icons\installer-wizard-large-175.bmp,{#Root}\assets\icons\installer-wizard-large-200.bmp
WizardSmallImageFile={#Root}\assets\icons\installer-wizard-small-100.bmp,{#Root}\assets\icons\installer-wizard-small-125.bmp,{#Root}\assets\icons\installer-wizard-small-150.bmp,{#Root}\assets\icons\installer-wizard-small-175.bmp,{#Root}\assets\icons\installer-wizard-small-200.bmp
SetupIconFile={#Root}\assets\icons\app.ico
UninstallDisplayIcon={app}\{#AppExe}
UninstallDisplayName={#AppName}
ChangesEnvironment=yes
CloseApplications=yes
RestartApplications=no
OutputDir={#Root}\dist
OutputBaseFilename=Apnoro-Setup-{#AppVersion}
SetupLogging=yes

[Messages]
SetupWindowTitle=Setup - %1

[Tasks]
Name: "parksites"; Description: "Create a Sites folder at %USERPROFILE%\Apnoro\Sites and park it"
Name: "addtopath"; Description: "Add the apnoro command to PATH"
; php/composer shims live in {app}\shims. When another PHP (Herd, XAMPP, ...) is already on PATH
; the user decides which php wins; the default keeps the existing one first.
Name: "shims"; Description: "Add Apnoro php and composer to PATH"; Check: not OtherPHPFound
Name: "shimsother"; Description: "Add Apnoro php and composer to PATH (found existing: {code:OtherPHPPath})"; Check: OtherPHPFound
Name: "shimsother\after"; Description: "After the existing php (it stays the default ""php"")"; Flags: exclusive; Check: OtherPHPFound
Name: "shimsother\first"; Description: "Before the existing php (Apnoro php becomes the default)"; Flags: exclusive unchecked; Check: OtherPHPFound
Name: "trustca"; Description: "Trust the Apnoro local HTTPS certificate"
Name: "autostart"; Description: "Start Apnoro when Windows starts"; Flags: unchecked
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"

[Dirs]
; Owner-only ACL is applied in CurStepChanged (SecureDataDir): the installing user gets Modify,
; other users get nothing (the dir holds binaries others would run and the MySQL root password).
Name: "{code:GetDataDir}"; Flags: uninsneveruninstall

[Files]
Source: "{#Root}\dist\app\{#AppExe}"; DestDir: "{app}"; Flags: ignoreversion; AfterInstall: WriteDataDirFile
Source: "{#Root}\dist\app\bin\*"; DestDir: "{app}\bin"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#Root}\dist\app\shims\*"; DestDir: "{app}\shims"; Flags: ignoreversion recursesubdirs createallsubdirs
; Runtimes only (apache\, php\<minor>\, mysql\, apps\, LICENSES\). User data (data\, conf\, certs\,
; config.json, php.ini) is generated by `apnoro setup` and never shipped, so upgrades cannot clobber it.
Source: "{#Root}\dist\payload\*"; DestDir: "{code:GetDataDir}"; Excludes: "\apps\phpmyadmin\config.inc.php"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#Root}\dist\payload\apps\phpmyadmin\config.inc.php"; DestDir: "{code:GetDataDir}\apps\phpmyadmin"; Flags: onlyifdoesntexist uninsneveruninstall
Source: "{#VCRedist}"; Flags: dontcopy

[Icons]
Name: "{autoprograms}\Apnoro"; Filename: "{app}\{#AppExe}"
Name: "{autodesktop}\Apnoro"; Filename: "{app}\{#AppExe}"; Tasks: desktopicon

[Registry]
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "Apnoro"; ValueData: """{app}\{#AppExe}"" --hidden"; Tasks: autostart; Flags: uninsdeletevalue

[Run]
Filename: "{app}\{#AppExe}"; Description: "Launch Apnoro"; Flags: postinstall nowait skipifsilent runasoriginaluser

[UninstallRun]
; close the tray app first so Apnoro.exe can be deleted (it would otherwise keep running)
Filename: "{sys}\taskkill.exe"; Parameters: "/F /IM {#AppExe}"; Flags: runhidden waituntilterminated; RunOnceId: "CloseApp"
Filename: "{app}\bin\apnoro.exe"; Parameters: "stop"; Flags: runhidden waituntilterminated skipifdoesntexist; RunOnceId: "StopServices"
Filename: "{app}\bin\apnoro.exe"; Parameters: "hosts clear"; Flags: runhidden waituntilterminated skipifdoesntexist; RunOnceId: "ClearHosts"
Filename: "{sys}\sc.exe"; Parameters: "stop {#HelperService}"; Flags: runhidden waituntilterminated; RunOnceId: "StopHelper"
Filename: "{app}\bin\apnoro-helper.exe"; Parameters: "uninstall"; Flags: runhidden waituntilterminated skipifdoesntexist; RunOnceId: "RemoveHelper"
Filename: "{sys}\certutil.exe"; Parameters: "-delstore Root ""Apnoro Local CA"""; Flags: runhidden waituntilterminated; RunOnceId: "UntrustCA"
; the GUI's "Trust HTTPS certificate" adds it to the current user's store
Filename: "{sys}\certutil.exe"; Parameters: "-user -delstore Root ""Apnoro Local CA"""; Flags: runhidden waituntilterminated; RunOnceId: "UntrustCAUser"

[InstallDelete]
; 1.0 pre-release layouts shipped the shims in bin\ (always on PATH)
Type: files; Name: "{app}\bin\php.exe"
Type: files; Name: "{app}\bin\composer.phar"
Type: files; Name: "{app}\bin\composer.bat"

[UninstallDelete]
Type: files; Name: "{app}\data-dir.txt"
; written by the helper service while it is being stopped/removed
Type: files; Name: "{app}\bin\apnoro-helper.log*"
Type: dirifempty; Name: "{app}\bin"
Type: dirifempty; Name: "{app}"

[Code]
const
  EnvKey = 'SYSTEM\CurrentControlSet\Control\Session Manager\Environment';
  UserEnvKey = 'Environment';
  VCKey = 'SOFTWARE\Microsoft\VisualStudio\14.0\VC\Runtimes\x64';
  DefaultDataDir = 'C:\Apnoro';

var
  DataDirPage: TInputDirWizardPage;
  MySQLPage: TInputQueryWizardPage;
  UninstallDataDir: string;

{ ---------- migration from AMPLS (the product's former name) ---------- }

const
  LegacyUninstKey = 'Software\Microsoft\Windows\CurrentVersion\Uninstall\{E601BE50-B1E9-4B4D-AB38-CBD52D524511}_is1';

function LegacyInstalled: Boolean;
begin
  Result := RegKeyExists(HKLM, LegacyUninstKey);
end;

{ The data folder AMPLS used: its data-dir.txt, else the value its installer remembered. }
function LegacyDataDir: string;
var
  Loc: string;
  S: AnsiString;
begin
  Result := '';
  if not LegacyInstalled then exit;
  if RegQueryStringValue(HKLM, LegacyUninstKey, 'InstallLocation', Loc) and
     LoadStringFromFile(AddBackslash(Loc) + 'data-dir.txt', S) then
    Result := Trim(String(S));
  if Result = '' then
    RegQueryStringValue(HKLM, LegacyUninstKey, 'Inno Setup CodeFile: DataDir', Result);
end;

{ Silently uninstall AMPLS, keeping its data: its "delete the data folder?" prompt
  defaults to No, which /SUPPRESSMSGBOXES answers. It stops its services, removes
  its helper service, hosts block, certificate and PATH entries. }
procedure RemoveLegacyInstall;
var
  U: string;
  Code, Waited: Integer;
begin
  if not RegQueryStringValue(HKLM, LegacyUninstKey, 'UninstallString', U) then exit;
  WizardForm.StatusLabel.Caption := 'Migrating your previous installation (your sites and databases are kept)...';
  Log('Uninstalling the previous installation: ' + U);
  if not Exec(RemoveQuotes(U), '/VERYSILENT /SUPPRESSMSGBOXES /NORESTART', '', SW_HIDE, ewWaitUntilTerminated, Code) then
  begin
    Log('Could not start the previous uninstaller');
    exit;
  end;
  { the Inno uninstaller relaunches itself from %TEMP%, so wait for its entry to go }
  Waited := 0;
  while LegacyInstalled and (Waited < 120000) do
  begin
    Sleep(500);
    Waited := Waited + 500;
  end;
  Log(Format('Previous installation removed (code %d, waited %d ms, still registered: %d)', [Code, Waited, Ord(LegacyInstalled)]));
end;

{ ---------- data dir ---------- }

function GetDataDir(Param: string): string;
begin
  if DataDirPage <> nil then
    Result := RemoveBackslashUnlessRoot(Trim(DataDirPage.Values[0]))
  else
    Result := DefaultDataDir;
end;

procedure InitializeWizard;
var
  Def: string;
begin
  DataDirPage := CreateInputDirPage(wpSelectDir,
    'Select Data Location',
    'Where should Apnoro keep Apache, PHP versions, MySQL databases and site configs?',
    'Setup will store Apnoro data in the following folder. Keep the path short and without spaces so Apache and MySQL behave.' + #13#10#13#10 +
    'Your databases and site configuration live here and are kept when you upgrade.',
    False, 'Apnoro');
  DataDirPage.Add('');
  { upgrade: default to the previous data dir; silent installs can pass /DATADIR=D:\Apnoro }
  Def := GetPreviousData('DataDir', '');
  if Def = '' then Def := LegacyDataDir;   { migrating from AMPLS: keep its data folder }
  if Def = '' then Def := DefaultDataDir;
  DataDirPage.Values[0] := ExpandConstant('{param:DATADIR|' + Def + '}');

  MySQLPage := CreateInputQueryPage(DataDirPage.ID,
    'MySQL Root Password',
    'Choose the password for the MySQL root user.',
    'MySQL only listens on this computer (127.0.0.1). Leave both fields empty for no password, like XAMPP. ' +
    'You can change it later in Apnoro under MySQL > Change password.');
  MySQLPage.Add('&Password:', True);
  MySQLPage.Add('&Confirm password:', True);
end;

procedure RegisterPreviousData(PreviousDataKey: Integer);
begin
  SetPreviousData(PreviousDataKey, 'DataDir', GetDataDir(''));
end;

function IsInside(Child, Parent: string): Boolean;
begin
  Child := AddBackslash(Uppercase(Child));
  Parent := AddBackslash(Uppercase(Parent));
  Result := Copy(Child, 1, Length(Parent)) = Parent;
end;

{ The password only applies to a fresh MySQL datadir; upgrades keep the existing one. }
function MySQLAlreadyInitialized: Boolean;
begin
  Result := DirExists(GetDataDir('') + '\data\mysql');
end;

function ShouldSkipPage(PageID: Integer): Boolean;
begin
  Result := (MySQLPage <> nil) and (PageID = MySQLPage.ID) and MySQLAlreadyInitialized;
end;

function NextButtonClick(CurPageID: Integer): Boolean;
var
  D, App: string;
begin
  Result := True;
  if (MySQLPage <> nil) and (CurPageID = MySQLPage.ID) and (MySQLPage.Values[0] <> MySQLPage.Values[1]) then
  begin
    SuppressibleMsgBox('The two MySQL passwords do not match.', mbError, MB_OK, IDOK);
    Result := False;
    exit;
  end;
  if CurPageID = DataDirPage.ID then
  begin
    D := GetDataDir('');
    App := RemoveBackslashUnlessRoot(WizardDirValue);
    if (Length(D) < 4) or (Copy(D, 2, 2) <> ':\') then
    begin
      SuppressibleMsgBox('Please choose a folder on a local drive, not a drive root (for example C:\Apnoro).', mbError, MB_OK, IDOK);
      Result := False;
    end
    else if Pos(' ', D) > 0 then
    begin
      SuppressibleMsgBox('The data folder must not contain spaces.' + #13#10 +
        'Apache and MySQL configuration break on paths with spaces. Please choose a path like C:\Apnoro.', mbError, MB_OK, IDOK);
      Result := False;
    end
    else if IsInside(D, App) or IsInside(App, D) then
    begin
      SuppressibleMsgBox('The data folder must be separate from the program folder (' + App + ').', mbError, MB_OK, IDOK);
      Result := False;
    end;
  end;
end;

procedure WriteDataDirFile;
begin
  if not SaveStringToFile(ExpandConstant('{app}\data-dir.txt'), GetDataDir(''), False) then
    Log('Failed to write data-dir.txt');
end;

{ ---------- VC++ runtime ---------- }

function NextVersionPart(var S: string): Integer;
var
  P: Integer;
begin
  P := Pos('.', S);
  if P = 0 then begin Result := StrToIntDef(S, 0); S := ''; end
  else begin Result := StrToIntDef(Copy(S, 1, P - 1), 0); Delete(S, 1, P); end;
end;

function VCRedistNeeded: Boolean;
var
  Installed, Major, Minor, Bld: Cardinal;
  S: string;
  WantMajor, WantMinor, WantBld: Integer;
begin
  S := '{#VCRedistVersion}';
  WantMajor := NextVersionPart(S);
  WantMinor := NextVersionPart(S);
  WantBld := NextVersionPart(S);
  Result := True;
  if RegQueryDWordValue(HKLM64, VCKey, 'Installed', Installed) and (Installed = 1) and
     RegQueryDWordValue(HKLM64, VCKey, 'Major', Major) and
     RegQueryDWordValue(HKLM64, VCKey, 'Minor', Minor) and
     RegQueryDWordValue(HKLM64, VCKey, 'Bld', Bld) then
  begin
    if Major <> WantMajor then Result := Major < WantMajor
    else if Minor <> WantMinor then Result := Minor < WantMinor
    else Result := Bld < WantBld;
    Log(Format('VC++ runtime installed: %d.%d.%d, bundled: {#VCRedistVersion}', [Major, Minor, Bld]));
  end;
end;

{ ---------- PATH ---------- }

function PathContains(PathValue, Dir: string): Boolean;
begin
  PathValue := ';' + Uppercase(PathValue) + ';';
  Result := (Pos(';' + Uppercase(Dir) + ';', PathValue) > 0) or
            (Pos(';' + Uppercase(Dir) + '\;', PathValue) > 0);
end;

function EnvRootKey(Root: Integer): string;
begin
  if Root = HKLM then Result := EnvKey else Result := UserEnvKey;
end;

{ Root: HKLM (system PATH, searched first) or HKCU (user PATH, searched after the system PATH). }
procedure AddToPath(Root: Integer; Dir: string; Prepend: Boolean);
var
  P: string;
begin
  if not RegQueryStringValue(Root, EnvRootKey(Root), 'Path', P) then P := '';
  if PathContains(P, Dir) then exit;
  if P = '' then
    P := Dir
  else if Prepend then
    P := Dir + ';' + P
  else
  begin
    if P[Length(P)] <> ';' then P := P + ';';
    P := P + Dir;
  end;
  if not RegWriteExpandStringValue(Root, EnvRootKey(Root), 'Path', P) then
    Log('Failed to update PATH: ' + Dir);
end;

procedure AddToSystemPath(Dir: string);
begin
  AddToPath(HKLM, Dir, False);
end;

{ ---------- existing PHP (Laravel Herd, XAMPP, ...) ---------- }

var
  OtherPHP: string;
  OtherPHPChecked: Boolean;

function FindOtherPHP: string;
var
  Herd: string;
begin
  Result := FileSearch('php.exe', GetEnv('PATH'));
  if Result = '' then Result := FileSearch('php.bat', GetEnv('PATH'));
  if Result = '' then
  begin
    { Herd adds itself to the user PATH, which an elevated setup may not see }
    Herd := ExpandConstant('{%USERPROFILE}\.config\herd\bin\php.bat');
    if FileExists(Herd) then Result := Herd;
  end;
  { ignore our own shim from a previous install, and AMPLS's (removed while migrating) }
  if (Result <> '') and IsInside(Result, ExpandConstant('{app}')) then Result := '';
  if Pos('\AMPLS\SHIMS\', Uppercase(Result)) > 0 then Result := '';
end;

function OtherPHPPath(Param: string): string;
begin
  if not OtherPHPChecked then
  begin
    OtherPHP := FindOtherPHP;
    OtherPHPChecked := True;
  end;
  Result := OtherPHP;
end;

function OtherPHPFound: Boolean;
begin
  Result := OtherPHPPath('') <> '';
end;

procedure RemoveFromPath(Root: Integer; Dir: string);
var
  P, Part, U, NewP: string;
  I: Integer;
begin
  if not RegQueryStringValue(Root, EnvRootKey(Root), 'Path', P) then exit;
  if not PathContains(P, Dir) then exit;
  U := Uppercase(Dir);
  NewP := '';
  P := P + ';';
  while P <> '' do
  begin
    I := Pos(';', P);
    Part := Copy(P, 1, I - 1);
    Delete(P, 1, I);
    if (Part <> '') and (Uppercase(Part) <> U) and (Uppercase(Part) <> U + '\') then
    begin
      if NewP <> '' then NewP := NewP + ';';
      NewP := NewP + Part;
    end;
  end;
  RegWriteExpandStringValue(Root, EnvRootKey(Root), 'Path', NewP);
end;

procedure RemoveFromSystemPath(Dir: string);
begin
  RemoveFromPath(HKLM, Dir);
end;

{ ---------- install steps ---------- }

function RunHidden(Exe, Params, Status: string): Integer;
begin
  if Status <> '' then WizardForm.StatusLabel.Caption := Status;
  Log('Running: "' + Exe + '" ' + Params);
  if not Exec(Exe, Params, '', SW_HIDE, ewWaitUntilTerminated, Result) then
    Result := -1;
  Log(Format('  exit code %d', [Result]));
end;

function PrepareToInstall(var NeedsRestart: Boolean): String;
var
  Code: Integer;
begin
  Result := '';
  { upgrade: stop running services and the helper so their binaries can be replaced }
  if FileExists(ExpandConstant('{app}\bin\apnoro.exe')) then
    Exec(ExpandConstant('{app}\bin\apnoro.exe'), 'stop', '', SW_HIDE, ewWaitUntilTerminated, Code);
  Exec(ExpandConstant('{sys}\sc.exe'), 'stop {#HelperService}', '', SW_HIDE, ewWaitUntilTerminated, Code);
  Exec(ExpandConstant('{sys}\taskkill.exe'), '/F /IM {#AppExe}', '', SW_HIDE, ewWaitUntilTerminated, Code);
  if LegacyInstalled then
    RemoveLegacyInstall;
end;

function SetupFlags: string;
begin
  Result := '';
  if WizardIsTaskSelected('parksites') then Result := Result + ' --park-default';
end;

{ Runs as the user who started setup (not the elevated admin), so the data dir,
  the Sites folder and the CA key belong to them. }
function RunAsUser(Exe, Params, Status: string): Integer;
begin
  if Status <> '' then WizardForm.StatusLabel.Caption := Status;
  Log('Running as original user: "' + Exe + '" ' + Params);
  if not ExecAsOriginalUser(Exe, Params, '', SW_HIDE, ewWaitUntilTerminated, Result) then
    Result := -1;
  Log(Format('  exit code %d', [Result]));
end;

{ Break inheritance (C:\ grants Authenticated Users Modify to new subfolders) and give
  only SYSTEM, Administrators and the installing user access. }
{ DOMAIN\user of the account that started setup. With over-the-shoulder UAC the elevated
  account differs, so ask the original user's own process (whoami) while the new data dir
  still inherits write access from C:\. }
function OriginalUserName(Home: string): string;
var
  F: string;
  S: AnsiString;
  Code: Integer;
begin
  Result := GetUserNameString;
  F := Home + '\installer-user.txt';
  if ExecAsOriginalUser(ExpandConstant('{sys}\cmd.exe'), '/c whoami > "' + F + '"', '', SW_HIDE, ewWaitUntilTerminated, Code)
     and LoadStringFromFile(F, S) and (Trim(String(S)) <> '') then
    Result := Trim(String(S));
  DeleteFile(F);
  Log('Data dir owner: ' + Result);
end;

procedure SecureDataDir(Home: string);
begin
  { Set the ACL on the root only, then make every child inherit it. Applying the
    (OI)(CI) grants with /T stamps them onto each file, where they do not grant
    execute: mysqld.exe / php.exe then fail with "Access is denied". }
  RunHidden(ExpandConstant('{sys}\icacls.exe'),
    '"' + Home + '" /inheritance:r /grant:r *S-1-5-18:(OI)(CI)F *S-1-5-32-544:(OI)(CI)F "' +
    OriginalUserName(Home) + '":(OI)(CI)M /C /Q', 'Securing the data folder...');
  RunHidden(ExpandConstant('{sys}\icacls.exe'), '"' + Home + '\*" /reset /T /C /Q', '');
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  Code: Integer;
  Home, Bin, Shims, PwFile, Params: string;
  PwLines: TArrayOfString;
begin
  if CurStep <> ssPostInstall then exit;
  Home := GetDataDir('');
  Bin := ExpandConstant('{app}\bin');
  WriteDataDirFile;
  WizardForm.ProgressGauge.Style := npbstMarquee;

  if VCRedistNeeded then
  begin
    ExtractTemporaryFile('vc_redist.x64.exe');
    Code := RunHidden(ExpandConstant('{tmp}\vc_redist.x64.exe'), '/install /quiet /norestart',
      'Installing the Microsoft Visual C++ runtime...');
    { 0 = ok, 1638 = newer already installed, 3010 = ok, reboot required }
    if (Code <> 0) and (Code <> 1638) and (Code <> 3010) then
      SuppressibleMsgBox(Format('The Microsoft Visual C++ runtime installer failed (code %d). Apache and PHP need it; ' +
        'install it from https://aka.ms/vs/17/release/vc_redist.x64.exe', [Code]), mbError, MB_OK, IDOK);
  end;

  if WizardIsTaskSelected('addtopath') then
    AddToSystemPath(Bin);
  { php/composer shims: an upgrade may change the choice, so clear both places first }
  Shims := ExpandConstant('{app}\shims');
  RemoveFromPath(HKLM, Shims);
  RemoveFromPath(HKCU, Shims);
  if WizardIsTaskSelected('shims') then
    AddToPath(HKLM, Shims, False)
  else if WizardIsTaskSelected('shimsother\first') then
    AddToPath(HKLM, Shims, True)     { system PATH, first: beats every other php }
  else if WizardIsTaskSelected('shimsother\after') then
    AddToPath(HKCU, Shims, False);   { end of the user PATH: existing php keeps winning }

  SecureDataDir(Home);

  { elevated: the helper must run before setup so setup's hosts request is applied by it }
  Code := RunHidden(Bin + '\apnoro-helper.exe', 'install --home "' + Home + '"',
    'Installing the Apnoro hosts helper service...');
  if Code = 0 then
    RunHidden(ExpandConstant('{sys}\sc.exe'), 'start {#HelperService}', '')
  else
    Log('apnoro-helper install failed; hosts edits will fall back to UAC prompts');

  { unelevated: never write as admin into a user-writable tree }
  { MySQL root password: handed over in a one-time file inside the (now owner-only)
    data dir, never on a command line; setup deletes it after reading. }
  PwFile := '';
  if (not MySQLAlreadyInitialized) and (MySQLPage.Values[0] <> '') then
  begin
    PwFile := Home + '\setup-mysql-password.txt';
    SetArrayLength(PwLines, 1);
    PwLines[0] := MySQLPage.Values[0];
    { UTF-8 (with BOM, CRLF); apnoro setup strips both }
    if not SaveStringsToUTF8File(PwFile, PwLines, False) then
    begin
      Log('Could not write the MySQL password file; MySQL will start without a password');
      PwFile := '';
    end;
  end;
  Params := 'setup --home "' + Home + '"' + SetupFlags;
  if PwFile <> '' then Params := Params + ' --mysql-password-file "' + PwFile + '"';
  Code := RunAsUser(Bin + '\apnoro.exe', Params,
    'Configuring Apache, PHP and MySQL (this can take a minute)...');
  if PwFile <> '' then DeleteFile(PwFile);
  if Code <> 0 then
    SuppressibleMsgBox(Format('Apnoro setup did not finish (code %d).' + #13#10#13#10 +
      'Details: %s\logs\setup.log' + #13#10#13#10 +
      'You can re-run it later from a terminal:  apnoro setup --home "%s"', [Code, Home, Home]), mbError, MB_OK, IDOK);

  { elevated: trust the CA the user just created (verified against its key, never created here) }
  if WizardIsTaskSelected('trustca') then
    RunHidden(Bin + '\apnoro.exe', 'trust --machine --home "' + Home + '"', 'Trusting the Apnoro HTTPS certificate...');

  WizardForm.ProgressGauge.Style := npbstNormal;
end;

{ ---------- uninstall ---------- }

function InitializeUninstall: Boolean;
var
  S: AnsiString;
begin
  Result := True;
  UninstallDataDir := '';
  if LoadStringFromFile(ExpandConstant('{app}\data-dir.txt'), S) then
    UninstallDataDir := Trim(String(S));
end;

function LooksLikeApnoroHome(D: string): Boolean;
begin
  Result := (Length(D) > 3) and DirExists(D) and
    (FileExists(D + '\config.json') or DirExists(D + '\apache') or DirExists(D + '\mysql'));
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep = usUninstall then
  begin
    RemoveFromSystemPath(ExpandConstant('{app}\bin'));
    RemoveFromPath(HKLM, ExpandConstant('{app}\shims'));
    RemoveFromPath(HKCU, ExpandConstant('{app}\shims'));
  end;

  if (CurUninstallStep = usPostUninstall) and (UninstallDataDir <> '') and LooksLikeApnoroHome(UninstallDataDir) then
  begin
    if SuppressibleMsgBox('Also delete the Apnoro data folder?' + #13#10#13#10 + UninstallDataDir + #13#10#13#10 +
      'This permanently removes ALL MySQL databases, site configs, certificates and logs stored there. ' +
      'Your project folders (Sites) are not touched.' + #13#10#13#10 +
      'Choose No to keep your data for a later reinstall.',
      mbConfirmation, MB_YESNO or MB_DEFBUTTON2, IDNO) = IDYES then
    begin
      if not DelTree(UninstallDataDir, True, True, True) then
        MsgBox('Some files in ' + UninstallDataDir + ' could not be removed. You can delete the folder manually.', mbInformation, MB_OK);
    end;
  end;
end;
